// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa0a9gCgs5n6YE7WS41qbpzR7sUHaFo90',
    appId: '1:280677427740:web:e24722888f3fb5107c8dd9',
    messagingSenderId: '280677427740',
    projectId: 'chat-app-e9143',
    authDomain: 'chat-app-e9143.firebaseapp.com',
    storageBucket: 'chat-app-e9143.firebasestorage.app',
    measurementId: 'G-31X16FVKBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXmCzo1aMbrEOcfadHKhhYFEftHXR1t4',
    appId: '1:280677427740:android:9c56f62b94db6ffe7c8dd9',
    messagingSenderId: '280677427740',
    projectId: 'chat-app-e9143',
    storageBucket: 'chat-app-e9143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLtYtnyj6_05ks-9H0hOEgyj88lj0tRI',
    appId: '1:280677427740:ios:69fc2c4f29f742cd7c8dd9',
    messagingSenderId: '280677427740',
    projectId: 'chat-app-e9143',
    storageBucket: 'chat-app-e9143.firebasestorage.app',
    iosBundleId: 'com.example.chatHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLtYtnyj6_05ks-9H0hOEgyj88lj0tRI',
    appId: '1:280677427740:ios:69fc2c4f29f742cd7c8dd9',
    messagingSenderId: '280677427740',
    projectId: 'chat-app-e9143',
    storageBucket: 'chat-app-e9143.firebasestorage.app',
    iosBundleId: 'com.example.chatHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa0a9gCgs5n6YE7WS41qbpzR7sUHaFo90',
    appId: '1:280677427740:web:98e9a455ebc80bae7c8dd9',
    messagingSenderId: '280677427740',
    projectId: 'chat-app-e9143',
    authDomain: 'chat-app-e9143.firebaseapp.com',
    storageBucket: 'chat-app-e9143.firebasestorage.app',
    measurementId: 'G-RRZEX6W7LH',
  );
}
